#!/usr/bin/env bash
# upload_stats_plots.sh — stub for cvmfs-testbed.
#
# The cvmfs-gateway statistics component calls this script to upload HTML
# statistics plots generated by the cvmfs-server package.  In the testbed the
# full cvmfs-server package is not installed inside the gateway container, so
# the real script is absent and the gateway logs an error on every transaction.
#
# This stub silences that error by providing the expected path.  It intentionally
# does nothing (the testbed uses Prometheus/Grafana for metrics, not these plots).
exit 0
